/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ    24000000U
#define BOARD_BOOTCLOCKPLL150M_CORE_CLOCK   150000000U

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

void FRDM_MCXN947InitBootClock(void);


#endif /* _CLOCK_CONFIG_H_ */

